// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT7WBnrhkdaXS_o1w8PPF2DYSrcYZw2Xk',
    appId: '1:1093872308638:web:316b7abeb8e2b98929868f',
    messagingSenderId: '1093872308638',
    projectId: 'stylehub-1cfee',
    authDomain: 'stylehub-1cfee.firebaseapp.com',
    storageBucket: 'stylehub-1cfee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeXfyB445b4h7rzOKF2pT6qAjN-msOssU',
    appId: '1:1093872308638:android:e9ceed395432bbdc29868f',
    messagingSenderId: '1093872308638',
    projectId: 'stylehub-1cfee',
    storageBucket: 'stylehub-1cfee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG0kvWtUR76B83pO68fCOeT2tg3HnyvJs',
    appId: '1:1093872308638:ios:e803ccb32fe04ca029868f',
    messagingSenderId: '1093872308638',
    projectId: 'stylehub-1cfee',
    storageBucket: 'stylehub-1cfee.firebasestorage.app',
    iosBundleId: 'com.example.stylehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG0kvWtUR76B83pO68fCOeT2tg3HnyvJs',
    appId: '1:1093872308638:ios:e803ccb32fe04ca029868f',
    messagingSenderId: '1093872308638',
    projectId: 'stylehub-1cfee',
    storageBucket: 'stylehub-1cfee.firebasestorage.app',
    iosBundleId: 'com.example.stylehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT7WBnrhkdaXS_o1w8PPF2DYSrcYZw2Xk',
    appId: '1:1093872308638:web:33657362d10665e529868f',
    messagingSenderId: '1093872308638',
    projectId: 'stylehub-1cfee',
    authDomain: 'stylehub-1cfee.firebaseapp.com',
    storageBucket: 'stylehub-1cfee.firebasestorage.app',
  );

}